# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl = https://localhost:7069

GET {{baseUrl}}/api/businesses
ApiKey : {{apiKey}}

###

PUT {{baseUrl}}/api/businesses/1
ApiKey : {{apiKey}}
Content-type: application/json

{
    "userId": 3,
    "name": "adamfoneil@proton.me",
    "contactName": "Adam O'Neil",
    "address": "2393 Sample Address",
    "city": "Yadkinville",
    "state": "AB",
    "zip": "39583",
    "nextInvoiceNumber": 1000,
    "hourlyRate": 75,
    "customers": [],
    "paymentMethods": [],
    "apiKeys": [],
    "id": 1
  }
