name: Set version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set version tag
      uses: adamfoneil/set-version@main

    - name: Debug outputs
      run: |
        echo "TAG: ${{ steps.set-version.outputs.tag }}"
        echo "SKIP: ${{ steps.set-version.outputs.skip }}"
